name: Deploy to FireBase Hosting and Cloud Function

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.MD"

jobs:
  # BUILD AND DEPLOY CLOUD FUNCTION
  build_and_deploy_cloud_function:
    name: Build and Deploy Cloud Function
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/functions

      - name: Create env file
        working-directory: ./frontend/functions
        run: |
          touch .env
          echo CMC_KEY=${{ secrets.CMC_KEY }} >> .env
          echo FINAGE_API_KEY=${{ secrets.FINAGE_API_KEY }} >> .env

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      # deploy to firebase
      - id: "deploy_cloud_function"
        name: Deploy to Firebase
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          runtime: "nodejs16"
          source_dir: "./frontend/functions"

  # BUILD STATIC WEBSITE
  build_web:
    name: Build Project To Use On Hosting
    runs-on: ubuntu-latest
    needs: build_and_deploy_cloud_function
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: create env file
        run: |
          touch .env
          echo FINAGE_API_KEY=${{ secrets.FINAGE_API_KEY }} >> .env
          echo CLOUD_FUNCTION_API_URL=${{ needs.build_and_deploy_cloud_function.outputs.url }} >> .env
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run generate
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./frontend/dist

  # DEPLOY WEBSITE
  deploy_web:
    name: Deploy Static Web to Firebase Hosting
    needs:
      - build_web
      - build_and_deploy_cloud_function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_PATH: "./frontend/"
